name: decoupler_heng
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - tqdm
  - pip:
    - adjustText
    - decoupler
    - matplotlib-venn
    - omnipath
    - pydeseq2
    - scanpy
    - scimap
    - wget